import type { TursoClient, InStatement } from './turso-client';

const DEFAULT_CATEGORIES = [
  { slug: 'food', name: '餐饮', icon: 'Utensils', color: '#ff9500', sort_order: 1, is_income: 0 },
  { slug: 'transport', name: '交通', icon: 'Car', color: '#007aff', sort_order: 2, is_income: 0 },
  { slug: 'shopping', name: '购物', icon: 'ShoppingBag', color: '#ff2d55', sort_order: 3, is_income: 0 },
  { slug: 'entertainment', name: '娱乐', icon: 'Gamepad2', color: '#af52de', sort_order: 4, is_income: 0 },
  { slug: 'housing', name: '住房', icon: 'Home', color: '#5ac8fa', sort_order: 5, is_income: 0 },
  { slug: 'medical', name: '医疗', icon: 'Heart', color: '#ff3b30', sort_order: 6, is_income: 0 },
  { slug: 'telecom', name: '通讯', icon: 'Smartphone', color: '#5856d6', sort_order: 7, is_income: 0 },
  { slug: 'education', name: '教育', icon: 'BookOpen', color: '#32ade6', sort_order: 8, is_income: 0 },
  { slug: 'utilities', name: '水电', icon: 'Zap', color: '#ffcc00', sort_order: 9, is_income: 0 },
  { slug: 'subscription', name: '订阅', icon: 'Repeat', color: '#ff6b6b', sort_order: 10, is_income: 0 },
  { slug: 'credit_card', name: '信用卡还款', icon: 'CreditCard', color: '#636366', sort_order: 11, is_income: 0 },
  { slug: 'transfer', name: '转账', icon: 'ArrowLeftRight', color: '#a2845e', sort_order: 12, is_income: 0 },
  { slug: 'transfer_self', name: '内部转账', icon: 'RefreshCw', color: '#c7c7cc', sort_order: 13, is_income: 0 },
  { slug: 'salary', name: '工资', icon: 'Banknote', color: '#30d158', sort_order: 1, is_income: 1 },
  { slug: 'bonus', name: '奖金', icon: 'Gift', color: '#34c759', sort_order: 2, is_income: 1 },
  { slug: 'refund', name: '退款', icon: 'RotateCcw', color: '#64d2ff', sort_order: 3, is_income: 1 },
  { slug: 'income_other', name: '其他收入', icon: 'ArrowDownToLine', color: '#30db5b', sort_order: 4, is_income: 1 },
  { slug: 'uncategorized', name: '未分类', icon: 'CircleDashed', color: '#8e8e93', sort_order: 99, is_income: 0 },
];

const DEFAULT_RULES = [
  { keyword: '美团', category_slug: 'food', priority: 10 },
  { keyword: '饿了么', category_slug: 'food', priority: 10 },
  { keyword: '肯德基', category_slug: 'food', priority: 10 },
  { keyword: '麦当劳', category_slug: 'food', priority: 10 },
  { keyword: '星巴克', category_slug: 'food', priority: 10 },
  { keyword: '瑞幸', category_slug: 'food', priority: 10 },
  { keyword: '餐饮', category_slug: 'food', priority: 5 },
  { keyword: '外卖', category_slug: 'food', priority: 5 },
  { keyword: '餐厅', category_slug: 'food', priority: 5 },
  { keyword: '食品', category_slug: 'food', priority: 5 },
  { keyword: '超市', category_slug: 'food', priority: 3 },
  { keyword: '便利店', category_slug: 'food', priority: 3 },
  { keyword: '奶茶', category_slug: 'food', priority: 5 },
  { keyword: '咖啡', category_slug: 'food', priority: 5 },
  { keyword: '火锅', category_slug: 'food', priority: 5 },
  { keyword: '烧烤', category_slug: 'food', priority: 5 },
  { keyword: '面包', category_slug: 'food', priority: 5 },
  { keyword: '水果', category_slug: 'food', priority: 5 },
  { keyword: '滴滴', category_slug: 'transport', priority: 10 },
  { keyword: '高德', category_slug: 'transport', priority: 10 },
  { keyword: '铁路', category_slug: 'transport', priority: 10 },
  { keyword: '12306', category_slug: 'transport', priority: 10 },
  { keyword: '地铁', category_slug: 'transport', priority: 10 },
  { keyword: '公交', category_slug: 'transport', priority: 10 },
  { keyword: '出租车', category_slug: 'transport', priority: 8 },
  { keyword: '打车', category_slug: 'transport', priority: 8 },
  { keyword: '加油', category_slug: 'transport', priority: 8 },
  { keyword: '停车', category_slug: 'transport', priority: 8 },
  { keyword: '高速', category_slug: 'transport', priority: 8 },
  { keyword: '航空', category_slug: 'transport', priority: 8 },
  { keyword: '机票', category_slug: 'transport', priority: 8 },
  { keyword: '携程', category_slug: 'transport', priority: 8 },
  { keyword: '哈啰', category_slug: 'transport', priority: 8 },
  { keyword: '淘宝', category_slug: 'shopping', priority: 10 },
  { keyword: '天猫', category_slug: 'shopping', priority: 10 },
  { keyword: '京东', category_slug: 'shopping', priority: 10 },
  { keyword: '拼多多', category_slug: 'shopping', priority: 10 },
  { keyword: '抖音商城', category_slug: 'shopping', priority: 10 },
  { keyword: '唯品会', category_slug: 'shopping', priority: 10 },
  { keyword: '购物', category_slug: 'shopping', priority: 5 },
  { keyword: '商城', category_slug: 'shopping', priority: 5 },
  { keyword: '电影', category_slug: 'entertainment', priority: 8 },
  { keyword: '游戏', category_slug: 'entertainment', priority: 8 },
  { keyword: 'Steam', category_slug: 'entertainment', priority: 10 },
  { keyword: '网易云', category_slug: 'entertainment', priority: 8 },
  { keyword: 'QQ音乐', category_slug: 'entertainment', priority: 8 },
  { keyword: '酒吧', category_slug: 'entertainment', priority: 8 },
  { keyword: 'KTV', category_slug: 'entertainment', priority: 8 },
  { keyword: '房租', category_slug: 'housing', priority: 10 },
  { keyword: '物业', category_slug: 'housing', priority: 10 },
  { keyword: '房贷', category_slug: 'housing', priority: 10 },
  { keyword: '自如', category_slug: 'housing', priority: 10 },
  { keyword: '链家', category_slug: 'housing', priority: 10 },
  { keyword: '医院', category_slug: 'medical', priority: 10 },
  { keyword: '药店', category_slug: 'medical', priority: 10 },
  { keyword: '药房', category_slug: 'medical', priority: 10 },
  { keyword: '诊所', category_slug: 'medical', priority: 8 },
  { keyword: '挂号', category_slug: 'medical', priority: 8 },
  { keyword: '中国移动', category_slug: 'telecom', priority: 10 },
  { keyword: '中国联通', category_slug: 'telecom', priority: 10 },
  { keyword: '中国电信', category_slug: 'telecom', priority: 10 },
  { keyword: '话费', category_slug: 'telecom', priority: 10 },
  { keyword: '流量', category_slug: 'telecom', priority: 8 },
  { keyword: '学费', category_slug: 'education', priority: 10 },
  { keyword: '培训', category_slug: 'education', priority: 8 },
  { keyword: '书店', category_slug: 'education', priority: 8 },
  { keyword: '课程', category_slug: 'education', priority: 8 },
  { keyword: '电费', category_slug: 'utilities', priority: 10 },
  { keyword: '水费', category_slug: 'utilities', priority: 10 },
  { keyword: '燃气', category_slug: 'utilities', priority: 10 },
  { keyword: '供暖', category_slug: 'utilities', priority: 10 },
  { keyword: '会员', category_slug: 'subscription', priority: 8 },
  { keyword: 'VIP', category_slug: 'subscription', priority: 8 },
  { keyword: '爱奇艺', category_slug: 'subscription', priority: 10 },
  { keyword: '腾讯视频', category_slug: 'subscription', priority: 10 },
  { keyword: '优酷', category_slug: 'subscription', priority: 10 },
  { keyword: 'B站', category_slug: 'subscription', priority: 10 },
  { keyword: 'Netflix', category_slug: 'subscription', priority: 10 },
  { keyword: 'Spotify', category_slug: 'subscription', priority: 10 },
  { keyword: '转账', category_slug: 'transfer', priority: 5 },
  { keyword: '红包', category_slug: 'transfer', priority: 5 },
  { keyword: '工资', category_slug: 'salary', priority: 10 },
  { keyword: '薪资', category_slug: 'salary', priority: 10 },
  { keyword: '奖金', category_slug: 'bonus', priority: 10 },
  { keyword: '退款', category_slug: 'refund', priority: 10 },
  { keyword: '退货', category_slug: 'refund', priority: 10 },
];

export async function seedCategories(db: TursoClient) {
  const count = await db.execute('SELECT COUNT(*) as cnt FROM categories');
  if ((count.rows[0] as unknown as { cnt: number }).cnt > 0) return;

  const stmts: InStatement[] = [];
  for (const c of DEFAULT_CATEGORIES) {
    stmts.push({
      sql: 'INSERT INTO categories (slug, name, icon, color, sort_order, is_income) VALUES (?, ?, ?, ?, ?, ?)',
      args: [c.slug, c.name, c.icon, c.color, c.sort_order, c.is_income],
    });
  }
  for (const r of DEFAULT_RULES) {
    stmts.push({
      sql: 'INSERT INTO category_rules (keyword, category_slug, source, priority) VALUES (?, ?, ?, ?)',
      args: [r.keyword, r.category_slug, 'default', r.priority],
    });
  }
  await db.batch(stmts, 'write');
}
